version: '2'

services:
  sparkMaster:
    image: analyticsci/openshift-spark:v2.1.0-metrics-poc
    container_name: sparkMaster
    ports:
      - "8081:8080"
      - "7077:7077"
  sparkWorker1:
    image: analyticsci/openshift-spark:v2.1.0-metrics-poc
    container_name: sparkWorker1
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://sparkMaster:7077
    links:
      - sparkMaster
    environment:
      - "SPARK_MASTER_ADDRESS=spark://sparkMaster:7077"
      - "SPARK_USER=bob"
