version: '2'

services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - /data/db:/data/db
#    ports:
#      - "27017:27017"
  zookeeper:
    image: bzcareer/docker-zookeeper
    container_name: zookeeper-coordination-service
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: bzcareer/docker-kafka
    container_name: kafka-messaging-service
    links:
      - zookeeper:zookeeper
    environment:
      - "KAFKA_SERVICE_SERVICE_HOST=zookeeper"
    ports:
      - "9092:9092"
      - "9999:9999"
  s3:
    image: minio/minio
    container_name: s3storage
    command: server /export
    ports:
      - "9000:9000"
  sparkMaster:
    image: radanalyticsio/openshift-spark
    container_name: sparkMaster
    ports:
      - "8081:8080"
      - "7077:7077"
  sparkWorker1:
    image: radanalyticsio/openshift-spark
    container_name: sparkWorker1
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://sparkMaster:7077
    ports:
      - "8082:8081"
    links:
      - sparkMaster:sparkMaster
    environment:
      - "SPARK_MASTER_ADDRESS=spark://sparkMaster:7077"
      - "SPARK_USER=bob"
  messaging-service:
    build:
      context: messaging-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - mongo:mongo
      - kafka:kafkaETL
    environment:
      - "KAFKA_URI=kafkaETL:9092"
      - "MONGODB_HOST=mongo"
      - "MONGODB_PORT=27017"
  spark-streaming-service:
    build:
      context: spark-streaming-service
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    links:
      - kafka:kafkabroker
      - sparkMaster:sparkMasterURL
    environment:
      - "KAFKA_URI=kafkabroker:9092"
      - "SPARK_MASTER_URL=spark://sparkMasterURL:7077"
      - "SPARK_USER=bob"
  prometheus-metrics:
    container_name: prometheus-metrics
    build:
      context: metrics
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    links:
      - kafka:kafkabrokerMetrics
      - sparkMaster:sparkMasterMetrics
  order-web-ui:
    container_name: order-web-ui
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    links:
      - messaging-service:messaging-service
      - mongo:mongodb
    environment:
      - "MONGO_URL=mongodb://mongodb:27017/sampledb"
      - "OPENSHIFT_DATAPIPELINE_CAMEL_URL=http://messaging-service:8080"
